// Remote video playback: stream normalisation (engine proxy, subtitles, audio),
// video-list cache, remembered server, and the <AnimeVideo> player component.
import React,{useEffect,useRef,useState}from'react'
import Hls from'hls.js'
import{t,plural}from'../i18n'
import{lsGet,lsSet}from'../lib/util'
import{NoticeText}from'../ui/common'
import{playerKeys,rememberVolume,restoreVolume,useVideoShortcuts}from'./videos'
import{mediaPosKey,readMediaPos,orderedEpisodes}from'../lib/media'
export type RemoteMediaMode='anime'|'series'|'movies'
export const REMOTE_PLAYER_CONFIG:Record<RemoteMediaMode,{positionPrefix:string;fallback:boolean;blocked:string[]}>= {
 anime:{positionPrefix:'anime',fallback:false,blocked:[]},
 series:{positionPrefix:'series',fallback:true,blocked:['streamingunity','streamingcommunity']},
 movies:{positionPrefix:'movie',fallback:true,blocked:['streamingunity','streamingcommunity']}
}
export function remoteMode(v:any):RemoteMediaMode{return v==='series'?'series':v==='movies'?'movies':'anime'}
// Episode video lists are cached for 10 minutes and the next episode is fetched in
// the background, so "Next" and episode re-clicks start without re-extracting.
export const videoListCache=new Map<string,{at:number,p:Promise<any>}>()
export function fetchVideosCached(sourceId:string,episodeUrl:string){const key=sourceId+'|'+episodeUrl;const hit=videoListCache.get(key);if(hit&&Date.now()-hit.at<10*60e3)return hit.p;const p=window.novelReader.miwayomiFetch('/api/v1/anime/'+encodeURIComponent(sourceId)+'/videos?url='+encodeURIComponent(episodeUrl));videoListCache.set(key,{at:Date.now(),p});p.then((d:any)=>{const n=Array.isArray(d)?d.length:(d?.videos||[]).length;if(!n)videoListCache.delete(key)},()=>videoListCache.delete(key));return p}
export function prefetchNextEpisode(media:any,ep:any,sourceId:string){try{const list=orderedEpisodes(media?.episodes||[]);const cur=String(ep?.url||ep?.path||'');const i=list.findIndex((x:any)=>String(x?.url||x?.path||'')===cur);const next=i>=0?list[i+1]:null;const url=next&&(next.url||next.path);if(!url||!sourceId)return;setTimeout(()=>{fetchVideosCached(sourceId,String(url)).catch(()=>{})},4000)}catch{}}
// The stream (server + quality) that last played for a title is remembered and
// tried first next time, so playback starts on a server known to work.
export const serverKey=(media:any)=>'prefServer:'+String(media?.id||media?.url||media?.name||'')
export function rememberServer(media:any,video:any){try{const title=String(video?.videoTitle||video?.title||video?.quality||'');if(media&&title)lsSet(serverKey(media),title)}catch{}}
export function preferRemembered(list:any[],media:any){const want=String(lsGet(serverKey(media))||'');if(!want||list.length<2)return list;const head=(x:string)=>x.split(' - ')[0].trim().toLowerCase(),kind=(x:string)=>(x.match(/\b(sub|dub|h-sub|s-sub|a-dub)\b/i)?.[1]||'').toLowerCase();const score=(v:any)=>{const tt=String(v?.videoTitle||v?.title||v?.quality||'');return tt===want?3:head(tt)===head(want)&&kind(tt)===kind(want)?2:head(tt)===head(want)?1:0};return list.map((v,i)=>({v,i,s:score(v)})).sort((a,b)=>b.s-a.s||a.i-b.i).map(x=>x.v)}
// Route extension subtitle files through the Miwayomi proxy (source headers / Referer).
export function proxySubtitleTracks(tracks:any,sourceId:string,headers:any){return (Array.isArray(tracks)?tracks:[]).map((t:any)=>{const su=String(t?.url||t?.file||t?.src||'');if(!/^https?:\/\//i.test(su))return t;const sh=Object.entries(t?.headers||headers||{}).map(([k,val])=>k+': '+String(val)).join('\n');return {...t,streamUrl:'http://127.0.0.1:4567/api/v1/proxy?sourceId='+encodeURIComponent(sourceId)+'&url='+encodeURIComponent(su)+'&headers='+encodeURIComponent(sh)}})}
// Sources that just failed with a dead host / timeout / block are skipped by the
// fallback search for 15 minutes instead of being waited on every time.
export const brokenSources=new Map<string,number>()
export const BROKEN_SOURCE_RE=/timed out|inconnu|unknown ?host|connection timed out|HTTP error 4\d\d|Cloudflare|ECONNREFUSED/i
export function normalizeRemoteVideos(videos:any[],sourceId:string,sourceName:string){const out:any[]=[];const preferred=videos.find((v:any)=>v?.preferred)||videos[0];for(const v of videos){const raw=String(v?.videoUrl||v?.url||v?.link||'');const headers=v?.headers||{};const lower=raw.toLowerCase();let stream='';if(/^https?:\/\//i.test(raw)){const headerText=Object.entries(headers).map(([k,val])=>k+': '+String(val)).join('\n');const qs='sourceId='+encodeURIComponent(sourceId)+'&url='+encodeURIComponent(raw)+'&headers='+encodeURIComponent(headerText);const hls=lower.includes('.m3u8')||/\/playlist(?:\/|\?|$)/i.test(raw)||/vixcloud\.co\/playlist/i.test(raw);stream='http://127.0.0.1:4567/api/v1/'+(hls?'hls':lower.includes('.mpd')?'dash':'proxy')+'?'+qs}else if(/^magnet:\?/i.test(raw)&&v===preferred){continue}if(!stream)continue;const audioTracks=(Array.isArray(v?.audioTracks)?v.audioTracks:[]).map((t:any)=>{const au=String(t?.url||t?.audioUrl||t?.src||'');if(!/^https?:\/\//i.test(au))return t;const ah=Object.entries(t?.headers||headers||{}).map(([k,val])=>k+': '+String(val)).join('\n');return {...t,streamUrl:'http://127.0.0.1:4567/api/v1/hls?sourceId='+encodeURIComponent(sourceId)+'&url='+encodeURIComponent(au)+'&headers='+encodeURIComponent(ah)}});const subtitleTracks=proxySubtitleTracks(v?.subtitleTracks,sourceId,headers);out.push({...v,audioTracks,subtitleTracks,streamUrl:stream,sourceName,unsupportedScheme:''})}return out}

export function AnimeVideo({video,mediaKey,onNext,onPrev,onUnsupported,variants,onVariant,onPlaying}:{video:any,mediaKey?:string,onPlaying?:()=>void,onNext?:()=>void,onPrev?:()=>void,onUnsupported?:()=>void,variants?:any[],onVariant?:(v:any)=>void}){
 const ref=useRef<HTMLVideoElement>(null),audioRef=useRef<HTMLAudioElement>(null),hlsRef=useRef<Hls|null>(null),audioHlsRef=useRef<Hls|null>(null),externalAudioStarted=useRef(false),lastSave=useRef(0),[playError,setPlayError]=useState('')
 const[hlsAudios,setHlsAudios]=useState<any[]>([]),[nowT,setNowT]=useState(0),[nextIn,setNextIn]=useState<number|null>(null),[elAudios,setElAudios]=useState<any[]>([]),[extSubs,setExtSubs]=useState<any[]>([]),[hlsSubs,setHlsSubs]=useState<any[]>([]),[audioIndex,setAudioIndex]=useState(0),[subIndex,setSubIndex]=useState(-1),[rate,setRate]=useState(()=>Number(localStorage.getItem('novelreader:player:rate')||'1'))
 const sourceAudios=Array.isArray(video?.audioTracks)?video.audioTracks:Array.isArray(video?.audio)?video.audio:[],sourceSubs=Array.isArray(video?.subtitleTracks)?video.subtitleTracks:Array.isArray(video?.subtitles)?video.subtitles:Array.isArray(video?.tracks)?video.tracks:[]
 const key=mediaKey||String(video?.streamUrl||'')
 const save=(el:HTMLVideoElement,done=false)=>{if(!key||!el.duration||!Number.isFinite(el.duration))return;localStorage.setItem(mediaPosKey(key),JSON.stringify({t:done?0:el.currentTime,d:el.duration,done:done||el.currentTime>el.duration-30,at:Date.now()}))}
 // Audio tracks embedded in a direct file (e.g. multi-audio MKV/MP4), exposed by the
 // AudioVideoTracks Blink feature enabled in electron/main.cjs.
 const elTrackList=(el:any)=>{const at=el?.audioTracks;return at?[...at].map((t:any,i:number)=>({name:t.label||'',lang:t.language||'',label:t.label||t.language||('Audio '+(i+1))})):[]}
 const enableElAudio=(el:any,i:number)=>{const at=el?.audioTracks;if(!at||!at[i])return;for(let n=0;n<at.length;n++)at[n].enabled=n===i;if(Number.isFinite(el.currentTime))el.currentTime=el.currentTime}
 const syncElementAudio=(el:any)=>{const list=elTrackList(el);if(list.length<2){setElAudios([]);return}setElAudios(list);const saved=String(localStorage.getItem('novelreader:player:audio')||'').toLowerCase();const pick=saved?list.findIndex((x:any)=>{const a=(x.name+' '+x.lang).toLowerCase();return a.includes(saved)||(!!x.lang&&saved.includes(x.lang.toLowerCase()))}):-1;if(pick>=0){enableElAudio(el,pick);setAudioIndex(pick)}else{const cur=[...el.audioTracks].findIndex((t:any)=>t.enabled);setAudioIndex(Math.max(0,cur))}console.log('[novelreader] embedded-audio-tracks',{tracks:list,selected:pick})}
 // External subtitle files provided by the extension (e.g. MegaPlay VTT tracks).
 // Fetched through the Miwayomi proxy (source headers) and served as blob URLs.
 useEffect(()=>{setExtSubs([]);const list=sourceSubs.filter((x:any)=>x?.streamUrl);if(!list.length)return;let alive=true;const urls:string[]=[]
  Promise.all(list.map(async(t:any,i:number)=>{try{const r=await fetch(String(t.streamUrl));if(!r.ok)throw Error('HTTP '+r.status);let text=(await r.text()).replace(/^\uFEFF/,'').replace(/\r/g,'');if(/^\s*\[Script Info\]/i.test(text))return null;if(!/^\s*WEBVTT/.test(text))text='WEBVTT\n\n'+text.replace(/(\d\d:\d\d:\d\d),(\d\d\d)/g,'$1.$2');const src=URL.createObjectURL(new Blob([text],{type:'text/vtt'}));urls.push(src);const name=String(t?.lang||t?.label||t?.language||('Subtitle '+(i+1)));return {src,name,label:name+' #'+(i+1),lang:name.slice(0,2).toLowerCase()}}catch(e:any){console.warn('[novelreader] subtitle load failed',t?.lang,e?.message||String(e));return null}}))
   .then(res=>{if(!alive)return;const ok=res.filter(Boolean) as any[];setExtSubs(ok);console.log('[novelreader] external-subtitles',ok.map(x=>x.name));const saved=String(localStorage.getItem('novelreader:player:subtitle')||'');if(saved==='off'||!ok.length){setSubIndex(-1);return}const want=(saved||'english').toLowerCase();const pick=Math.max(0,ok.findIndex(x=>x.name.toLowerCase().includes(want)));setSubIndex(pick)})
  return()=>{alive=false;urls.forEach(u=>URL.revokeObjectURL(u))}
 },[video?.streamUrl,sourceSubs.map((x:any)=>String(x?.streamUrl||'')).join('|')])
 const showExtSub=(list:any[],i:number)=>{const el=ref.current;if(!el)return;const want=i>=0?list[i]?.label:null;for(let n=0;n<el.textTracks.length;n++){const t=el.textTracks[n];if(list.some(x=>x.label===t.label))t.mode=t.label===want?'showing':'disabled'}}
 useEffect(()=>{if(extSubs.length&&!hlsSubs.length)showExtSub(extSubs,subIndex)},[extSubs,subIndex,hlsSubs.length])
 // Intro/outro markers from the source (Video.timestamps: Opening / Ending).
 const stamps=(Array.isArray(video?.timestamps)?video.timestamps:[]).filter((x:any)=>Number(x?.end)>Number(x?.start))
 const seg=stamps.find((x:any)=>nowT>=Number(x.start)&&nowT<Number(x.end)-1)
 const segLabel=seg?(/open|intro/i.test(String(seg.type)+' '+String(seg.name))?t('Skip intro'):/end|outro|credit/i.test(String(seg.type)+' '+String(seg.name))?t('Skip credits'):t('Skip')):''
 // Auto-play the next episode after a short, cancellable countdown.
 useEffect(()=>{if(nextIn==null)return;if(nextIn<=0){setNextIn(null);onNext?.();return}const id=setTimeout(()=>setNextIn(n=>n==null?null:n-1),1000);return()=>clearTimeout(id)},[nextIn])
 useVideoShortcuts(ref,!!video?.streamUrl,{onNext,onPrev})
 useEffect(()=>{const el=ref.current;if(!el||!video?.streamUrl)return;externalAudioStarted.current=false;setPlayError('');setNowT(0);setNextIn(null);setHlsAudios([]);setElAudios([]);setHlsSubs([]);setAudioIndex(0);setSubIndex(-1);const url=String(video.streamUrl);const raw=String(video.videoUrl||video.url||video.link||'').toLowerCase();const streamRaw=String(video.streamUrl||'').toLowerCase();let hls:Hls|null=null
  const ready=()=>{restoreVolume(el);syncElementAudio(el);const p=readMediaPos(key);if(p&&!p.done&&p.t>5&&p.t<(el.duration||Infinity)-10)el.currentTime=p.t;if(!externalAudioStarted.current&&sourceAudios.some((x:any)=>x?.streamUrl)){const preferred=Math.max(0,sourceAudios.findIndex((x:any)=>/english/i.test(String(x?.lang||x?.language||x?.name||x?.label||''))));externalAudioStarted.current=true;console.log('[novelreader] external-audio-autostart',{preferred,lang:sourceAudios[preferred]?.lang||sourceAudios[preferred]?.language||''});setTimeout(()=>setAudio(preferred),0)}}
  const syncTracks=()=>{if(!hls)return;const aa=[...(hls.audioTracks||[])],ss=[...(hls.subtitleTracks||[])];setHlsAudios(aa);setHlsSubs(ss);const ai=hls.audioTrack>=0?hls.audioTrack:(aa.length?0:-1);if(ai>=0&&hls.audioTrack!==ai)hls.audioTrack=ai;setAudioIndex(ai>=0?ai:0);setSubIndex(hls.subtitleTrack??-1);console.log('[novelreader] hls-tracks',{audioTrack:hls.audioTrack,audioTracks:aa.map((x:any,i:number)=>({i,name:x?.name,lang:x?.lang,default:x?.default,groupId:x?.groupId,url:x?.url})),subtitleTrack:hls.subtitleTrack,subtitleTracks:ss.map((x:any,i:number)=>({i,name:x?.name,lang:x?.lang,default:x?.default,groupId:x?.groupId,url:x?.url}))})}
  const logHlsManifest=async()=>{if(!import.meta.env.DEV)return;try{const r=await fetch(url);const body=await r.text();const all=body.split(/\r?\n/).filter(Boolean),lines=all.slice(0,80);const tags=lines.filter(x=>x.startsWith('#EXT-X-STREAM-INF')||x.startsWith('#EXT-X-MEDIA')||x.startsWith('#EXT-X-MAP')||x.startsWith('#EXT-X-KEY'));const media=all.filter(x=>!x.startsWith('#')).slice(0,3);console.log('[novelreader] hls-manifest',{status:r.status,type:r.headers.get('content-type'),tags,media,preview:lines.slice(0,30)});const codecs=tags.flatMap(x=>Array.from(x.matchAll(/CODECS="([^"]+)"/g)).map(m=>m[1]));console.log('[novelreader] hls-codecs',{codecs:[...new Set(codecs)]});console.log('[novelreader] media-capabilities',{aac:el.canPlayType('audio/mp4; codecs="mp4a.40.2"'),ac3:el.canPlayType('audio/mp4; codecs="ac-3"'),eac3:el.canPlayType('audio/mp4; codecs="ec-3"'),mp3:el.canPlayType('audio/mpeg')})}catch(e:any){console.warn('[novelreader] hls-manifest probe failed',e?.message||String(e))}}
  el.addEventListener('loadedmetadata',ready)
  if((raw.includes('.m3u8')||raw.includes('/playlist')||streamRaw.includes('/api/v1/hls?'))&&Hls.isSupported()){hls=new Hls({maxBufferLength:60});hlsRef.current=hls;hls.loadSource(url);hls.attachMedia(el);hls.on(Hls.Events.MANIFEST_PARSED,()=>{syncTracks();logHlsManifest();el.muted=false;if(el.volume===0)el.volume=.8;el.play().catch(()=>{})});hls.on(Hls.Events.AUDIO_TRACKS_UPDATED,syncTracks);hls.on(Hls.Events.SUBTITLE_TRACKS_UPDATED,syncTracks);hls.on(Hls.Events.BUFFER_CODECS,(_e,data:any)=>{const audio=data?.audio,videoTrack=data?.video;console.log('[novelreader] hls-buffer-codecs',{audio:audio?{codec:audio.codec,container:audio.container,levelCodec:audio.levelCodec,metadata:audio.metadata}:null,video:videoTrack?{codec:videoTrack.codec,container:videoTrack.container,levelCodec:videoTrack.levelCodec}:null});if(!audio){console.warn('[novelreader] hls-no-audio',{message:'No audio elementary stream was found in the HLS media segments.',videoCodec:videoTrack?.codec||null,sourceAudioMetadata:sourceAudios});setPlayError(t('This stream contains video but no audio stream. Trying another quality/source may provide audio.'))}if(audio?.codec){const c=String(audio.codec).toLowerCase();const unsupported=(c.includes('ac-3')||c.includes('ac3')||c.includes('ec-3')||c.includes('eac3'))&&!el.canPlayType('audio/mp4; codecs="'+audio.codec+'"');if(unsupported)setPlayError('Audio codec '+audio.codec+' is not supported by this Electron build. Video can play, but this stream needs local audio transcoding.') }});
  hls.on(Hls.Events.AUDIO_TRACK_SWITCHED,(_e,d:any)=>{setAudioIndex(Number(d?.id??hls?.audioTrack??0))});hls.on(Hls.Events.SUBTITLE_TRACK_SWITCH,(_e,d:any)=>{setSubIndex(Number(d?.id??hls?.subtitleTrack??-1))});let netFails=0;hls.on(Hls.Events.ERROR,(_evt,data:any)=>{if(!data.fatal)return;if(data.type===Hls.ErrorTypes.NETWORK_ERROR){netFails++;const code=data?.response?.code;console.warn('[novelreader] hls-network-error',{details:data?.details,code,attempt:netFails});if(netFails>=2&&onUnsupported){setPlayError(t('This video server is not responding{code}. Trying another stream…',{code:code?' (HTTP '+code+')':''}));hls?.destroy();setTimeout(()=>onUnsupported(),250);return}if(netFails>=2){setPlayError(t('This video server is not responding{code}. Pick another quality or server.',{code:code?' (HTTP '+code+')':''}));hls?.destroy();return}hls?.startLoad()}else if(data.type===Hls.ErrorTypes.MEDIA_ERROR)hls?.recoverMediaError();else{setPlayError(t('The video stream stopped because the HLS player could not recover.'));hls?.destroy()}})}
  else{hlsRef.current=null;el.src=url;el.play().catch(()=>{})}
  return()=>{save(el);el.removeEventListener('loadedmetadata',ready);hls?.destroy();hlsRef.current=null;el.removeAttribute('src');el.load()}
 },[video?.streamUrl,key])
 const choices=(variants||[]).filter(Boolean),label=(v:any,i:number)=>String(v.videoTitle||v.title||v.quality||v.resolution||('Stream '+(i+1)))
 // Sources like Anichi publish sub and dub as separate streams ("HD-1 - Sub - 1080p" /
 // "HD-1 - Dub - 1080p"); offer them as an Audio choice that switches stream.
 const AUDIO_KIND=/(?:^|[\s\-\[(|])(H-Sub|S-Sub|SoftSub|A-Dub|Sub|Dub)(?=$|[\s\-\])|])/i
 const kindOf=(v:any,i:number)=>{const m=label(v,i).match(AUDIO_KIND);return m?m[1]:''}
 const kinds=[...new Set(choices.map((v:any,i:number)=>kindOf(v,i)).filter(Boolean))] as string[]
 const kindName=(k:string)=>/dub/i.test(k)?t('{kind} (dubbed audio)',{kind:k}):t('{kind} (original audio)',{kind:k})
 const currentKind=kindOf(video,choices.indexOf(video))
 const switchKind=(k:string)=>{const cur=label(video,choices.indexOf(video));const target=cur.replace(AUDIO_KIND,(m:string,g:string)=>m.replace(g,k));const v=choices.find((x:any,i:number)=>label(x,i)===target)||choices.find((x:any,i:number)=>kindOf(x,i)===k);if(!v||v===video)return;localStorage.setItem('novelreader:player:quality',label(v,choices.indexOf(v)));onVariant?.(v)}
 const audios=hlsAudios.length?hlsAudios:sourceAudios,subs=hlsSubs.length?hlsSubs:sourceSubs,trackName=(x:any,fallback:string)=>String(x?.name||x?.label||x?.lang||x?.language||fallback)
 const useElAudio=!hlsAudios.length&&!sourceAudios.some((x:any)=>x?.streamUrl)&&elAudios.length>1
 const setAudio=(i:number)=>{setAudioIndex(i);if(useElAudio){const chosen=elAudios[i];const l=String(chosen?.name||chosen?.lang||'');if(l)localStorage.setItem('novelreader:player:audio',l);enableElAudio(ref.current,i);return}const chosen=sourceAudios[i]||hlsAudios[i];const chosenLang=String(chosen?.lang||chosen?.language||chosen?.name||chosen?.label||'');if(chosenLang)localStorage.setItem('novelreader:player:audio',chosenLang);const el=ref.current as any;if(el){el.muted=false;if(el.volume===0)el.volume=.8}const h=hlsRef.current;if(h&&hlsAudios.length){h.audioTrack=i;h.startLoad();return}if(sourceAudios[i]?.streamUrl){const ae=audioRef.current;if(!ae)return;externalAudioStarted.current=true;console.log('[novelreader] external-audio-start',{index:i,lang:sourceAudios[i]?.lang||sourceAudios[i]?.language||'',url:sourceAudios[i]?.streamUrl});audioHlsRef.current?.destroy();audioHlsRef.current=null;ae.pause();ae.removeAttribute('src');const au=String(sourceAudios[i].streamUrl);if(Hls.isSupported()){const ah=new Hls({maxBufferLength:60});audioHlsRef.current=ah;ah.loadSource(au);ah.attachMedia(ae);ah.on(Hls.Events.MANIFEST_PARSED,()=>{if(ref.current){ae.currentTime=ref.current.currentTime;ae.volume=ref.current.volume;ae.muted=false;ref.current.muted=true;console.log('[novelreader] external-audio-ready',{index:i,lang:sourceAudios[i]?.lang||sourceAudios[i]?.language||'',url:au});if(!ref.current.paused)ae.play().catch((e:any)=>console.warn('[novelreader] external-audio-play failed',e?.message||String(e)))}});ah.on(Hls.Events.ERROR,(_e,d:any)=>{console[d?.fatal?'error':'warn']('[novelreader] external-audio-hls-error',{fatal:d?.fatal,type:d?.type,details:d?.details,response:d?.response,reason:d?.reason})})}else{ae.src=au;ae.currentTime=el.currentTime;el.muted=true;ae.play().catch(()=>{})}return}if(el?.audioTracks)for(let n=0;n<el.audioTracks.length;n++)el.audioTracks[n].enabled=n===i}
 const setSubtitle=(i:number)=>{setSubIndex(i);if(i<0)localStorage.setItem('novelreader:player:subtitle','off');else{const chosen=(hlsSubs.length?hlsSubs:extSubs.length?extSubs:sourceSubs)[i];localStorage.setItem('novelreader:player:subtitle',String(chosen?.name||chosen?.lang||chosen?.language||chosen?.label||i))}const h=hlsRef.current;if(h&&hlsSubs.length){h.subtitleTrack=i;return}if(extSubs.length){showExtSub(extSubs,i);return}const el=ref.current;if(!el)return;for(let n=0;n<el.textTracks.length;n++)el.textTracks[n].mode=n===i?'showing':'disabled'}
 const selectableAudios=hlsAudios.length?audios:useElAudio?elAudios:sourceAudios.filter((x:any)=>x?.streamUrl),selectableSubs=hlsSubs.length?subs:extSubs
 useEffect(()=>{if(!video?.streamUrl||hlsAudios.length||externalAudioStarted.current)return;const savedAudio=localStorage.getItem('novelreader:player:audio')||'English';const preferred=Math.max(0,sourceAudios.findIndex((x:any)=>String(x?.lang||x?.language||x?.name||x?.label||'').toLowerCase().includes(savedAudio.toLowerCase())));if(sourceAudios[preferred]?.streamUrl){externalAudioStarted.current=true;console.log('[novelreader] external-audio-autostart',{preferred,lang:sourceAudios[preferred]?.lang||sourceAudios[preferred]?.language||''});setAudio(preferred)}},[video?.streamUrl,hlsAudios.length,sourceAudios.map((x:any)=>String(x?.streamUrl||'')).join('|')])
 useEffect(()=>()=>{audioHlsRef.current?.destroy();audioHlsRef.current=null},[])

 const showKinds=!selectableAudios.length&&kinds.length>1
 return <div className="remote-player">{(choices.length>1||selectableAudios.length||selectableSubs.length)?<div className="player-trackbar">{showKinds&&<label>{t('Audio')}<select value={currentKind} onChange={e=>switchKind(e.target.value)}>{kinds.map(k=><option key={k} value={k}>{kindName(k)}</option>)}</select></label>}{choices.length>1&&<label>{t('Quality')}<select value={choices.indexOf(video)} onChange={e=>{const v=choices[Number(e.target.value)];localStorage.setItem('novelreader:player:quality',label(v,Number(e.target.value)));onVariant?.(v)}}>{choices.map((v:any,i:number)=><option key={i} value={i}>{label(v,i)}</option>)}</select></label>}{selectableAudios.length>0&&<label>{t('Audio')}<select value={Math.min(audioIndex,selectableAudios.length-1)} onChange={e=>setAudio(Number(e.target.value))}>{selectableAudios.map((x:any,i:number)=><option key={i} value={i}>{trackName(x,'Audio '+(i+1))}</option>)}</select></label>}{selectableSubs.length>0&&<label>{t('Subtitles')}<select value={subIndex} onChange={e=>setSubtitle(Number(e.target.value))}><option value={-1}>{t('Off')}</option>{selectableSubs.map((x:any,i:number)=><option key={i} value={i}>{trackName(x,'Subtitle '+(i+1))}</option>)}</select></label>}<label>{t('Speed')}<select value={rate} onChange={e=>{const r=Number(e.target.value);setRate(r);localStorage.setItem('novelreader:player:rate',String(r));if(ref.current)ref.current.playbackRate=r;if(audioRef.current)audioRef.current.playbackRate=r}}><option value={0.5}>0.5×</option><option value={0.75}>0.75×</option><option value={1}>1×</option><option value={1.25}>1.25×</option><option value={1.5}>1.5×</option><option value={1.75}>1.75×</option><option value={2}>2×</option></select></label></div>:null}<audio ref={audioRef} style={{display:'none'}}/><div className="player-stage"><video ref={ref} controls autoPlay playsInline style={{width:'100%',maxHeight:'70vh',background:'#000'}}
  onLoadedMetadata={e=>{e.currentTarget.playbackRate=rate;if(audioRef.current)audioRef.current.playbackRate=rate}} onVolumeChange={e=>{rememberVolume(e.currentTarget);if(audioRef.current)audioRef.current.volume=e.currentTarget.volume}}
  onTimeUpdate={e=>{setNowT(e.currentTarget.currentTime);const ae=audioRef.current;if(ae&&audioHlsRef.current&&Math.abs(ae.currentTime-e.currentTarget.currentTime)>.5)ae.currentTime=e.currentTarget.currentTime;const now=Date.now();if(now-lastSave.current>4000){lastSave.current=now;save(e.currentTarget)}}}
  onPlaying={()=>onPlaying?.()} onPlay={()=>{const ae=audioRef.current;if(ae&&audioHlsRef.current){ae.currentTime=ref.current?.currentTime||0;ae.play().catch(()=>{})}}} onPause={e=>{audioRef.current?.pause();save(e.currentTarget)}}
  onEnded={e=>{save(e.currentTarget,true);if(onNext)setNextIn(5)}}
  onError={e=>{const c=e.currentTarget.error?.code;if(c===4&&onUnsupported){setPlayError(t('This quality is not supported by the built-in player. Trying another stream…'));setTimeout(()=>onUnsupported(),250);return}setPlayError(c===4?t('This stream uses a video or audio format that the built-in player cannot decode.'):t('The video stream could not be played. Try another source or quality.'))}}>{extSubs.map((t:any)=><track key={t.src} kind="subtitles" src={t.src} label={t.label} srcLang={t.lang}/>)}</video>
  {seg&&nextIn==null&&<button className="player-skip" onClick={()=>{const el=ref.current;if(el)el.currentTime=Number(seg.end)}}>{segLabel+' ⏭'}</button>}
  {nextIn!=null&&<div className="player-next" role="status"><span>{t('Next episode in {n} s',{n:nextIn})}</span><button className="primary" onClick={()=>{setNextIn(null);onNext?.()}}>{t('Play now')}</button><button onClick={()=>setNextIn(null)}>{t('Cancel')}</button></div>}</div>
  {playError&&<div className="anime-toast error"><NoticeText text={playError}/><button onClick={()=>setPlayError('')}>×</button></div>}
  <div className="player-row"><div className="libraryactions"><button disabled={!onPrev} onClick={()=>onPrev?.()}>{'← '+t('Previous')}</button><button disabled={!onNext} onClick={()=>onNext?.()}>{t('Next')+' →'}</button></div><small className="player-hint">{playerKeys()} · {t('N/P next/previous')}</small></div>
 </div>
}

