import { test, expect } from '@playwright/test'
import { open, nav } from './helpers'

test('global search: live progress, default languages, grouped results, add in place', async ({ page }) => {
  await open(page, { library: [], slowSources: true })
  await nav(page, 'Global Search')
  // Default languages = UI language (en) + English + Multi: 12 + 2 sources.
  await expect(page.locator('.langcount')).toHaveText('14 sources selected')
  await page.fill('.search-main input', 'shadow slave')
  await page.locator('.search-main button').click()
  await expect(page.locator('.search-main button')).toHaveText('Stop')
  await expect(page.locator('.searchstatus.running')).toContainText('Searching')
  await expect(page.locator('.searchstatus:not(.running)')).toContainText('Search finished: 14 sources checked.', { timeout: 15_000 })
  await expect(page.locator('.searchstatus')).toContainText('1 source did not answer.')
  expect(await page.evaluate(() => new Set((window as any).__calls.search).size)).toBe(14)
  await expect(page.locator('.resultcard h3')).toHaveText(['Shadow Slave', 'Shadow Slave Side Stories'])
  await expect(page.locator('.resultcard').first()).toContainText(/Found on \d+ sources/)
  await page.locator('.resultcard').first().locator('.resultactions .primary').click()
  await expect(page.locator('.search-toast.ok')).toContainText('“Shadow Slave” was added to your library.')
  await expect(page.locator('.resultcard').first().locator('.inlib')).toBeVisible()
  await nav(page, 'Library')
  await expect(page.locator('.libcard h2')).toHaveText(['Shadow Slave'])
})

test('global search: stop, all languages, recent searches', async ({ page }) => {
  await open(page, { library: [], slowSources: true })
  await nav(page, 'Global Search')
  await page.fill('.search-main input', 'lord of mysteries')
  await page.locator('.search-main button').click()
  await page.locator('.search-main button', { hasText: 'Stop' }).click()
  await expect(page.locator('.searchstatus')).toContainText('Search stopped')
  await page.locator('.langbar .chip.ghost').click()
  await expect(page.locator('.langcount')).toHaveText('22 sources selected')
  await page.reload()
  await expect(page.locator('.recent .chip')).toHaveText(['lord of mysteries'])
  await expect(page.locator('.langcount')).toHaveText('22 sources selected')
})

test('sources page: health from searches and manual test', async ({ page }) => {
  await open(page, { library: [] })
  await nav(page, 'Global Search')
  await page.fill('.search-main input', 'shadow slave')
  await page.locator('.search-main button').click()
  await expect(page.locator('.searchstatus:not(.running)')).toBeVisible({ timeout: 15_000 })
  await page.waitForTimeout(400)
  await nav(page, 'Sources')
  await expect(page.locator('.sourcerow')).toHaveCount(22)
  await expect(page.locator('.shelftab', { hasText: 'Working' })).toContainText('13')
  await expect(page.locator('.shelftab', { hasText: 'Failing' })).toContainText('1')
  await page.locator('.shelftab', { hasText: 'Not tested yet' }).click()
  const row = page.locator('.sourcerow').first()
  await row.locator('button').click()
  await expect(page.locator('.shelftab', { hasText: 'Not tested yet' })).toContainText('7')
  await expect(page.locator('.sourcerow button', { hasText: 'Install' })).toHaveCount(0)
})
