const test = require('node:test')
const assert = require('node:assert')
const fs = require('fs'), os = require('os'), path = require('path')
const { createOfflineStore } = require('../../electron/offline.cjs')

test('offline chapters: save, read, list, usage, remove', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nr-offline-'))
  const store = createOfflineStore({ app: { getPath: () => dir } })
  assert.equal(await store.get('royalroad:/fiction/1', '/c/1'), null)
  await store.save('royalroad:/fiction/1', '/c/1', '<p>One</p>', 'Mother of Learning')
  await store.save('royalroad:/fiction/1', '/c/2', '<p>Two</p>')
  await store.save('other:/x', '/c/1', '<p>Other</p>')
  assert.equal(await store.get('royalroad:/fiction/1', '/c/2'), '<p>Two</p>')
  assert.deepEqual((await store.list('royalroad:/fiction/1')).sort(), ['/c/1', '/c/2'])
  const u = await store.usage()
  assert.equal(u.chapters, 3); assert.equal(u.novels, 2); assert.ok(u.bytes > 0)
  await store.remove('royalroad:/fiction/1')
  assert.deepEqual(await store.list('royalroad:/fiction/1'), [])
  assert.equal(await store.get('other:/x', '/c/1'), '<p>Other</p>')
  await assert.rejects(store.save('a', '/c', '   '), /Empty chapter/)
  await assert.rejects(store.save('', '/c', 'x'), /Invalid novel id/)
  await store.clearAll()
  assert.equal((await store.usage()).chapters, 0)
})
